// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-2:94814c35-23aa-4259-84bd-a06494a72ac5';
var aws_cognito_region = 'us-east-2';
var aws_mobile_analytics_app_id = 'f03039ba5c87465984ee9635c55f5ae6';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'a25e7435-74e2-4a74-8f63-695656030e1c';
var aws_project_name = 'Itinerari';
var aws_project_region = 'us-east-2';
var aws_resource_name_prefix = 'itinerari-mobilehub-1189393028';
var aws_user_files = 'enable';
var aws_user_files_s3_bucket = 'itinerari-userfiles-mobilehub-1189393028';
var aws_user_files_s3_bucket_region = 'us-east-2';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
